import type { DetailedProduct, Review } from "@/api";

export const mockProducts: DetailedProduct[] = [
  {
    id: 1,
    name: "Cyberpunk 2077",
    price: 199.99,
    logoId: "logo-cyberpunk",
    platform: { id: 1, name: "Steam" },
    stock: 150,
    discountPercentage: 20,
    releaseDate: "2020-12-10",
    descriptionPl: "Futurystyczna gra RPG w otwartym świecie Night City.",
    descriptionEn: "A futuristic open-world RPG set in Night City.",
    visible: true,
    deleted: null,
    producent: { id: 1, name: "CD Projekt RED" },
    type: { id: 1, name: "RPG" },
    categories: [
      { id: 1, name: "Action" },
      { id: 2, name: "Open World" },
    ],
  },
  {
    id: 2,
    name: "The Witcher 3: Wild Hunt",
    price: 89.99,
    logoId: "logo-witcher3",
    platform: { id: 2, name: "GOG" },
    stock: 200,
    discountPercentage: 50,
    releaseDate: "2015-05-19",
    descriptionPl: "Epicka gra RPG w świecie Wiedźmina.",
    descriptionEn: "An epic RPG set in the Witcher universe.",
    visible: true,
    deleted: null,
    producent: { id: 1, name: "CD Projekt RED" },
    type: { id: 1, name: "RPG" },
    categories: [
      { id: 3, name: "Fantasy" },
      { id: 4, name: "Adventure" },
    ],
  },
  {
    id: 3,
    name: "Elden Ring",
    price: 249.99,
    logoId: "logo-eldenring",
    platform: { id: 1, name: "Steam" },
    stock: 75,
    discountPercentage: 0,
    releaseDate: "2022-02-25",
    descriptionPl: "Trudna gra akcji RPG od twórców Dark Souls.",
    descriptionEn: "A challenging action RPG from the creators of Dark Souls.",
    visible: true,
    deleted: null,
    producent: { id: 2, name: "FromSoftware" },
    type: { id: 1, name: "RPG" },
    categories: [
      { id: 1, name: "Action" },
      { id: 3, name: "Fantasy" },
    ],
  },
  {
    id: 4,
    name: "Baldur's Gate 3",
    price: 229.99,
    logoId: "logo-bg3",
    platform: { id: 1, name: "Steam" },
    stock: 100,
    discountPercentage: 10,
    releaseDate: "2023-08-03",
    descriptionPl: "Kolejna część kultowej serii RPG opartej na D&D.",
    descriptionEn: "The next entry in the classic D&D-based RPG series.",
    visible: false,
    deleted: null,
    producent: { id: 3, name: "Larian Studios" },
    type: { id: 1, name: "RPG" },
    categories: [
      { id: 3, name: "Fantasy" },
      { id: 5, name: "Strategy" },
    ],
  },
];

export const mockReviews: Review[] = [
  {
    id: 1,
    productId: 1,
    userId: 101,
    content: "Świetna gra, polecam!",
    rating: 5,
    status: "PENDING",
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date("2024-11-02"),
  },
  {
    id: 2,
    productId: 1,
    userId: 102,
    content: "Dużo bugów, ale fabularnie świetna.",
    rating: 4,
    status: "APPROVED",
    createdAt: new Date("2024-11-02"),
    updatedAt: new Date("2024-11-03"),
  },
  {
    id: 3,
    productId: 2,
    userId: 103,
    content: "Najlepsza gra RPG!",
    rating: 5,
    status: "APPROVED",
    createdAt: new Date("2024-11-03"),
    updatedAt: new Date("2024-11-04"),
  },
  {
    id: 4,
    productId: 3,
    userId: 104,
    content: "Zbyt trudna dla mnie.",
    rating: 2,
    status: "PENDING",
    createdAt: new Date("2024-11-04"),
    updatedAt: new Date("2024-11-05"),
  },
];
