/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsTypeIndexRouteImport } from './routes/products/type/index'
import { Route as ProductsPlatformIndexRouteImport } from './routes/products/platform/index'
import { Route as ProductsCategoryIndexRouteImport } from './routes/products/category/index'
import { Route as ProductsTypeTypeIdRouteImport } from './routes/products/type/$typeId'
import { Route as ProductsPlatformPlatformIdRouteImport } from './routes/products/platform/$platformId'
import { Route as ProductsCategoryCategoryIdRouteImport } from './routes/products/category/$categoryId'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsTypeIndexRoute = ProductsTypeIndexRouteImport.update({
  id: '/products/type/',
  path: '/products/type/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPlatformIndexRoute = ProductsPlatformIndexRouteImport.update({
  id: '/products/platform/',
  path: '/products/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryIndexRoute = ProductsCategoryIndexRouteImport.update({
  id: '/products/category/',
  path: '/products/category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsTypeTypeIdRoute = ProductsTypeTypeIdRouteImport.update({
  id: '/products/type/$typeId',
  path: '/products/type/$typeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPlatformPlatformIdRoute =
  ProductsPlatformPlatformIdRouteImport.update({
    id: '/products/platform/$platformId',
    path: '/products/platform/$platformId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsCategoryCategoryIdRoute =
  ProductsCategoryCategoryIdRouteImport.update({
    id: '/products/category/$categoryId',
    path: '/products/category/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/products': typeof ProductsIndexRoute
  '/products/category/$categoryId': typeof ProductsCategoryCategoryIdRoute
  '/products/platform/$platformId': typeof ProductsPlatformPlatformIdRoute
  '/products/type/$typeId': typeof ProductsTypeTypeIdRoute
  '/products/category': typeof ProductsCategoryIndexRoute
  '/products/platform': typeof ProductsPlatformIndexRoute
  '/products/type': typeof ProductsTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/products': typeof ProductsIndexRoute
  '/products/category/$categoryId': typeof ProductsCategoryCategoryIdRoute
  '/products/platform/$platformId': typeof ProductsPlatformPlatformIdRoute
  '/products/type/$typeId': typeof ProductsTypeTypeIdRoute
  '/products/category': typeof ProductsCategoryIndexRoute
  '/products/platform': typeof ProductsPlatformIndexRoute
  '/products/type': typeof ProductsTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/products/': typeof ProductsIndexRoute
  '/products/category/$categoryId': typeof ProductsCategoryCategoryIdRoute
  '/products/platform/$platformId': typeof ProductsPlatformPlatformIdRoute
  '/products/type/$typeId': typeof ProductsTypeTypeIdRoute
  '/products/category/': typeof ProductsCategoryIndexRoute
  '/products/platform/': typeof ProductsPlatformIndexRoute
  '/products/type/': typeof ProductsTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/products'
    | '/products/category/$categoryId'
    | '/products/platform/$platformId'
    | '/products/type/$typeId'
    | '/products/category'
    | '/products/platform'
    | '/products/type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/products'
    | '/products/category/$categoryId'
    | '/products/platform/$platformId'
    | '/products/type/$typeId'
    | '/products/category'
    | '/products/platform'
    | '/products/type'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/products/'
    | '/products/category/$categoryId'
    | '/products/platform/$platformId'
    | '/products/type/$typeId'
    | '/products/category/'
    | '/products/platform/'
    | '/products/type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsCategoryCategoryIdRoute: typeof ProductsCategoryCategoryIdRoute
  ProductsPlatformPlatformIdRoute: typeof ProductsPlatformPlatformIdRoute
  ProductsTypeTypeIdRoute: typeof ProductsTypeTypeIdRoute
  ProductsCategoryIndexRoute: typeof ProductsCategoryIndexRoute
  ProductsPlatformIndexRoute: typeof ProductsPlatformIndexRoute
  ProductsTypeIndexRoute: typeof ProductsTypeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/type/': {
      id: '/products/type/'
      path: '/products/type'
      fullPath: '/products/type'
      preLoaderRoute: typeof ProductsTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/platform/': {
      id: '/products/platform/'
      path: '/products/platform'
      fullPath: '/products/platform'
      preLoaderRoute: typeof ProductsPlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/category/': {
      id: '/products/category/'
      path: '/products/category'
      fullPath: '/products/category'
      preLoaderRoute: typeof ProductsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/type/$typeId': {
      id: '/products/type/$typeId'
      path: '/products/type/$typeId'
      fullPath: '/products/type/$typeId'
      preLoaderRoute: typeof ProductsTypeTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/platform/$platformId': {
      id: '/products/platform/$platformId'
      path: '/products/platform/$platformId'
      fullPath: '/products/platform/$platformId'
      preLoaderRoute: typeof ProductsPlatformPlatformIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/category/$categoryId': {
      id: '/products/category/$categoryId'
      path: '/products/category/$categoryId'
      fullPath: '/products/category/$categoryId'
      preLoaderRoute: typeof ProductsCategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsCategoryCategoryIdRoute: ProductsCategoryCategoryIdRoute,
  ProductsPlatformPlatformIdRoute: ProductsPlatformPlatformIdRoute,
  ProductsTypeTypeIdRoute: ProductsTypeTypeIdRoute,
  ProductsCategoryIndexRoute: ProductsCategoryIndexRoute,
  ProductsPlatformIndexRoute: ProductsPlatformIndexRoute,
  ProductsTypeIndexRoute: ProductsTypeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
