/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ErrorIndexRouteImport } from './routes/error/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ProductsTypeIndexRouteImport } from './routes/products/type/index'
import { Route as ProductsPlatformIndexRouteImport } from './routes/products/platform/index'
import { Route as ProductsCategoryIndexRouteImport } from './routes/products/category/index'
import { Route as ErrorRoleIndexRouteImport } from './routes/error/role/index'
import { Route as ErrorLoginIndexRouteImport } from './routes/error/login/index'
import { Route as CartSuccessIndexRouteImport } from './routes/cart/success/index'
import { Route as CartCancelIndexRouteImport } from './routes/cart/cancel/index'
import { Route as AccountSettingsIndexRouteImport } from './routes/account/settings/index'
import { Route as AccountReviewsIndexRouteImport } from './routes/account/reviews/index'
import { Route as AccountPurchasesIndexRouteImport } from './routes/account/purchases/index'
import { Route as AccountLoyaltyIndexRouteImport } from './routes/account/loyalty/index'
import { Route as AccountKeysIndexRouteImport } from './routes/account/keys/index'
import { Route as ProductsTypeTypeIdRouteImport } from './routes/products/type/$typeId'
import { Route as ProductsPlatformPlatformIdRouteImport } from './routes/products/platform/$platformId'
import { Route as ProductsCategoryCategoryIdRouteImport } from './routes/products/category/$categoryId'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsTypeIndexRoute = ProductsTypeIndexRouteImport.update({
  id: '/products/type/',
  path: '/products/type/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPlatformIndexRoute = ProductsPlatformIndexRouteImport.update({
  id: '/products/platform/',
  path: '/products/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryIndexRoute = ProductsCategoryIndexRouteImport.update({
  id: '/products/category/',
  path: '/products/category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoleIndexRoute = ErrorRoleIndexRouteImport.update({
  id: '/error/role/',
  path: '/error/role/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorLoginIndexRoute = ErrorLoginIndexRouteImport.update({
  id: '/error/login/',
  path: '/error/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartSuccessIndexRoute = CartSuccessIndexRouteImport.update({
  id: '/cart/success/',
  path: '/cart/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartCancelIndexRoute = CartCancelIndexRouteImport.update({
  id: '/cart/cancel/',
  path: '/cart/cancel/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsIndexRoute = AccountSettingsIndexRouteImport.update({
  id: '/account/settings/',
  path: '/account/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountReviewsIndexRoute = AccountReviewsIndexRouteImport.update({
  id: '/account/reviews/',
  path: '/account/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPurchasesIndexRoute = AccountPurchasesIndexRouteImport.update({
  id: '/account/purchases/',
  path: '/account/purchases/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoyaltyIndexRoute = AccountLoyaltyIndexRouteImport.update({
  id: '/account/loyalty/',
  path: '/account/loyalty/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountKeysIndexRoute = AccountKeysIndexRouteImport.update({
  id: '/account/keys/',
  path: '/account/keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsTypeTypeIdRoute = ProductsTypeTypeIdRouteImport.update({
  id: '/products/type/$typeId',
  path: '/products/type/$typeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPlatformPlatformIdRoute =
  ProductsPlatformPlatformIdRouteImport.update({
    id: '/products/platform/$platformId',
    path: '/products/platform/$platformId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsCategoryCategoryIdRoute =
  ProductsCategoryCategoryIdRouteImport.update({
    id: '/products/category/$categoryId',
    path: '/products/category/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/error': typeof ErrorIndexRoute
  '/products': typeof ProductsIndexRoute
  '/support': typeof SupportIndexRoute
  '/products/category/$categoryId': typeof ProductsCategoryCategoryIdRoute
  '/products/platform/$platformId': typeof ProductsPlatformPlatformIdRoute
  '/products/type/$typeId': typeof ProductsTypeTypeIdRoute
  '/account/keys': typeof AccountKeysIndexRoute
  '/account/loyalty': typeof AccountLoyaltyIndexRoute
  '/account/purchases': typeof AccountPurchasesIndexRoute
  '/account/reviews': typeof AccountReviewsIndexRoute
  '/account/settings': typeof AccountSettingsIndexRoute
  '/cart/cancel': typeof CartCancelIndexRoute
  '/cart/success': typeof CartSuccessIndexRoute
  '/error/login': typeof ErrorLoginIndexRoute
  '/error/role': typeof ErrorRoleIndexRoute
  '/products/category': typeof ProductsCategoryIndexRoute
  '/products/platform': typeof ProductsPlatformIndexRoute
  '/products/type': typeof ProductsTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/error': typeof ErrorIndexRoute
  '/products': typeof ProductsIndexRoute
  '/support': typeof SupportIndexRoute
  '/products/category/$categoryId': typeof ProductsCategoryCategoryIdRoute
  '/products/platform/$platformId': typeof ProductsPlatformPlatformIdRoute
  '/products/type/$typeId': typeof ProductsTypeTypeIdRoute
  '/account/keys': typeof AccountKeysIndexRoute
  '/account/loyalty': typeof AccountLoyaltyIndexRoute
  '/account/purchases': typeof AccountPurchasesIndexRoute
  '/account/reviews': typeof AccountReviewsIndexRoute
  '/account/settings': typeof AccountSettingsIndexRoute
  '/cart/cancel': typeof CartCancelIndexRoute
  '/cart/success': typeof CartSuccessIndexRoute
  '/error/login': typeof ErrorLoginIndexRoute
  '/error/role': typeof ErrorRoleIndexRoute
  '/products/category': typeof ProductsCategoryIndexRoute
  '/products/platform': typeof ProductsPlatformIndexRoute
  '/products/type': typeof ProductsTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/cart/': typeof CartIndexRoute
  '/error/': typeof ErrorIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/products/category/$categoryId': typeof ProductsCategoryCategoryIdRoute
  '/products/platform/$platformId': typeof ProductsPlatformPlatformIdRoute
  '/products/type/$typeId': typeof ProductsTypeTypeIdRoute
  '/account/keys/': typeof AccountKeysIndexRoute
  '/account/loyalty/': typeof AccountLoyaltyIndexRoute
  '/account/purchases/': typeof AccountPurchasesIndexRoute
  '/account/reviews/': typeof AccountReviewsIndexRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/cart/cancel/': typeof CartCancelIndexRoute
  '/cart/success/': typeof CartSuccessIndexRoute
  '/error/login/': typeof ErrorLoginIndexRoute
  '/error/role/': typeof ErrorRoleIndexRoute
  '/products/category/': typeof ProductsCategoryIndexRoute
  '/products/platform/': typeof ProductsPlatformIndexRoute
  '/products/type/': typeof ProductsTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/products/$productId'
    | '/account'
    | '/admin'
    | '/cart'
    | '/error'
    | '/products'
    | '/support'
    | '/products/category/$categoryId'
    | '/products/platform/$platformId'
    | '/products/type/$typeId'
    | '/account/keys'
    | '/account/loyalty'
    | '/account/purchases'
    | '/account/reviews'
    | '/account/settings'
    | '/cart/cancel'
    | '/cart/success'
    | '/error/login'
    | '/error/role'
    | '/products/category'
    | '/products/platform'
    | '/products/type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/products/$productId'
    | '/account'
    | '/admin'
    | '/cart'
    | '/error'
    | '/products'
    | '/support'
    | '/products/category/$categoryId'
    | '/products/platform/$platformId'
    | '/products/type/$typeId'
    | '/account/keys'
    | '/account/loyalty'
    | '/account/purchases'
    | '/account/reviews'
    | '/account/settings'
    | '/cart/cancel'
    | '/cart/success'
    | '/error/login'
    | '/error/role'
    | '/products/category'
    | '/products/platform'
    | '/products/type'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/products/$productId'
    | '/account/'
    | '/admin/'
    | '/cart/'
    | '/error/'
    | '/products/'
    | '/support/'
    | '/products/category/$categoryId'
    | '/products/platform/$platformId'
    | '/products/type/$typeId'
    | '/account/keys/'
    | '/account/loyalty/'
    | '/account/purchases/'
    | '/account/reviews/'
    | '/account/settings/'
    | '/cart/cancel/'
    | '/cart/success/'
    | '/error/login/'
    | '/error/role/'
    | '/products/category/'
    | '/products/platform/'
    | '/products/type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CartIndexRoute: typeof CartIndexRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  ProductsCategoryCategoryIdRoute: typeof ProductsCategoryCategoryIdRoute
  ProductsPlatformPlatformIdRoute: typeof ProductsPlatformPlatformIdRoute
  ProductsTypeTypeIdRoute: typeof ProductsTypeTypeIdRoute
  AccountKeysIndexRoute: typeof AccountKeysIndexRoute
  AccountLoyaltyIndexRoute: typeof AccountLoyaltyIndexRoute
  AccountPurchasesIndexRoute: typeof AccountPurchasesIndexRoute
  AccountReviewsIndexRoute: typeof AccountReviewsIndexRoute
  AccountSettingsIndexRoute: typeof AccountSettingsIndexRoute
  CartCancelIndexRoute: typeof CartCancelIndexRoute
  CartSuccessIndexRoute: typeof CartSuccessIndexRoute
  ErrorLoginIndexRoute: typeof ErrorLoginIndexRoute
  ErrorRoleIndexRoute: typeof ErrorRoleIndexRoute
  ProductsCategoryIndexRoute: typeof ProductsCategoryIndexRoute
  ProductsPlatformIndexRoute: typeof ProductsPlatformIndexRoute
  ProductsTypeIndexRoute: typeof ProductsTypeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/type/': {
      id: '/products/type/'
      path: '/products/type'
      fullPath: '/products/type'
      preLoaderRoute: typeof ProductsTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/platform/': {
      id: '/products/platform/'
      path: '/products/platform'
      fullPath: '/products/platform'
      preLoaderRoute: typeof ProductsPlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/category/': {
      id: '/products/category/'
      path: '/products/category'
      fullPath: '/products/category'
      preLoaderRoute: typeof ProductsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/role/': {
      id: '/error/role/'
      path: '/error/role'
      fullPath: '/error/role'
      preLoaderRoute: typeof ErrorRoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/login/': {
      id: '/error/login/'
      path: '/error/login'
      fullPath: '/error/login'
      preLoaderRoute: typeof ErrorLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/success/': {
      id: '/cart/success/'
      path: '/cart/success'
      fullPath: '/cart/success'
      preLoaderRoute: typeof CartSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/cancel/': {
      id: '/cart/cancel/'
      path: '/cart/cancel'
      fullPath: '/cart/cancel'
      preLoaderRoute: typeof CartCancelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/': {
      id: '/account/settings/'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reviews/': {
      id: '/account/reviews/'
      path: '/account/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/purchases/': {
      id: '/account/purchases/'
      path: '/account/purchases'
      fullPath: '/account/purchases'
      preLoaderRoute: typeof AccountPurchasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/loyalty/': {
      id: '/account/loyalty/'
      path: '/account/loyalty'
      fullPath: '/account/loyalty'
      preLoaderRoute: typeof AccountLoyaltyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/keys/': {
      id: '/account/keys/'
      path: '/account/keys'
      fullPath: '/account/keys'
      preLoaderRoute: typeof AccountKeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/type/$typeId': {
      id: '/products/type/$typeId'
      path: '/products/type/$typeId'
      fullPath: '/products/type/$typeId'
      preLoaderRoute: typeof ProductsTypeTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/platform/$platformId': {
      id: '/products/platform/$platformId'
      path: '/products/platform/$platformId'
      fullPath: '/products/platform/$platformId'
      preLoaderRoute: typeof ProductsPlatformPlatformIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/category/$categoryId': {
      id: '/products/category/$categoryId'
      path: '/products/category/$categoryId'
      fullPath: '/products/category/$categoryId'
      preLoaderRoute: typeof ProductsCategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  CartIndexRoute: CartIndexRoute,
  ErrorIndexRoute: ErrorIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  ProductsCategoryCategoryIdRoute: ProductsCategoryCategoryIdRoute,
  ProductsPlatformPlatformIdRoute: ProductsPlatformPlatformIdRoute,
  ProductsTypeTypeIdRoute: ProductsTypeTypeIdRoute,
  AccountKeysIndexRoute: AccountKeysIndexRoute,
  AccountLoyaltyIndexRoute: AccountLoyaltyIndexRoute,
  AccountPurchasesIndexRoute: AccountPurchasesIndexRoute,
  AccountReviewsIndexRoute: AccountReviewsIndexRoute,
  AccountSettingsIndexRoute: AccountSettingsIndexRoute,
  CartCancelIndexRoute: CartCancelIndexRoute,
  CartSuccessIndexRoute: CartSuccessIndexRoute,
  ErrorLoginIndexRoute: ErrorLoginIndexRoute,
  ErrorRoleIndexRoute: ErrorRoleIndexRoute,
  ProductsCategoryIndexRoute: ProductsCategoryIndexRoute,
  ProductsPlatformIndexRoute: ProductsPlatformIndexRoute,
  ProductsTypeIndexRoute: ProductsTypeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
